apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\hp\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: geo-location-service
  name: geo-location-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: geo-location-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\hp\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: geo-location-service
    spec:
      containers:
        - env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo-db:27017/SOA
          image: geo-location-service
          name: geo-location-service
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
