apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\hp\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: timetable-service
  name: timetable-service
spec:
  ports:
    - name: "8181"
      port: 8181
      targetPort: 8080
  selector:
    io.kompose.service: timetable-service
status:
  loadBalancer: {}
